import os
import sys
sys.path.insert(1, os.path.join(sys.path[0], '../utils'))
import numpy as np
import argparse
import librosa
import matplotlib.pyplot as plt
import torch
import matplotlib
matplotlib.rcParams['font.family'] = 'DejaVu Sans'
import csv

from utilities import create_folder, get_filename
from models import *
from pytorch_utils import move_data_to_device
# import config # Temporarily remove config import

# Load labels directly
current_script_dir = os.path.dirname(os.path.abspath(__file__))
project_root = os.path.dirname(os.path.dirname(current_script_dir)) # Go up from pytorch to aed and then to source
metadata_file_path = os.path.join(project_root, 'aed', 'metadata', 'class_labels_indices.csv')

labels = []
with open(metadata_file_path, 'r') as f:
    reader = csv.reader(f, delimiter=',')
    lines = list(reader)

for i1 in range(1, len(lines)):
    label = lines[i1][2]
    labels.append(label)

classes_num = len(labels)


def get_russian_labels():
    """Возвращает словарь соответствия английских меток русским"""
    return {
        'Speech': 'Речь',
        'Male speech, man speaking': 'Мужская речь',
        'Female speech, woman speaking': 'Женская речь',
        'Child speech, kid speaking': 'Детская речь',
        'Conversation': 'Разговор',
        'Narration, monologue': 'Монолог',
        'Babbling': 'Лепет',
        'Speech synthesizer': 'Синтезатор речи',
        'Shout': 'Крик',
        'Bellow': 'Рев',
        'Whoop': 'Вопль',
        'Yell': 'Визг',
        'Battle cry': 'Боевой клич',
        'Children shouting': 'Детские крики',
        'Screaming': 'Визг',
        'Whispering': 'Шепот',
        'Laughter': 'Смех',
        'Baby laughter': 'Детский смех',
        'Giggle': 'Хихиканье',
        'Snicker': 'Усмешка',
        'Belly laugh': 'Громкий смех',
        'Chuckle, chortle': 'Хохот',
        'Crying, sobbing': 'Плач',
        'Baby cry, infant cry': 'Детский плач',
        'Whimper': 'Хныканье',
        'Wail, moan': 'Стон',
        'Sigh': 'Вздох',
        'Singing': 'Пение',
        'Choir': 'Хор',
        'Yodeling': 'Йодль',
        'Chant': 'Напев',
        'Mantra': 'Мантра',
        'Male singing': 'Мужское пение',
        'Female singing': 'Женское пение',
        'Child singing': 'Детское пение',
        'Synthetic singing': 'Синтетическое пение',
        'Rapping': 'Рэп',
        'Humming': 'Гудение',
        'Groan': 'Стон',
        'Grunt': 'Ворчание',
        'Whistling': 'Свист',
        'Breathing': 'Дыхание',
        'Wheeze': 'Хрип',
        'Snoring': 'Храп',
        'Gasp': 'Вздох',
        'Pant': 'Задыхание',
        'Snort': 'Фырканье',
        'Cough': 'Кашель',
        'Throat clearing': 'Прочистка горла',
        'Sneeze': 'Чих',
        'Sniff': 'Шмыганье',
        'Run': 'Бег',
        'Shuffle': 'Шарканье',
        'Walk, footsteps': 'Шаги',
        'Chewing, mastication': 'Жевание',
        'Biting': 'Укус',
        'Gargling': 'Полоскание',
        'Stomach rumble': 'Урчание в животе',
        'Burping, eructation': 'Отрыжка',
        'Hiccup': 'Икота',
        'Fart': 'Пердеж',
        'Hands': 'Руки',
        'Finger snapping': 'Щелчки пальцами',
        'Clapping': 'Аплодисменты',
        'Heart sounds, heartbeat': 'Сердцебиение',
        'Heart murmur': 'Шум в сердце',
        'Cheering': 'Приветствия',
        'Applause': 'Аплодисменты',
        'Chatter': 'Болтовня',
        'Crowd': 'Толпа',
        'Hubbub, speech noise, speech babble': 'Гул толпы',
        'Children playing': 'Играющие дети',
        'Animal': 'Животное',
        'Domestic animals, pets': 'Домашние животные',
        'Dog': 'Собака',
        'Bark': 'Лай',
        'Yip': 'Тявканье',
        'Howl': 'Вой',
        'Bow-wow': 'Гав-гав',
        'Growling': 'Рычание',
        'Whimper (dog)': 'Скуление (собака)',
        'Cat': 'Кошка',
        'Purr': 'Мурлыканье',
        'Meow': 'Мяу',
        'Hiss': 'Шипение',
        'Caterwaul': 'Вой кошки',
        'Livestock, farm animals, working animals': 'Скот, фермерские животные',
        'Horse': 'Лошадь',
        'Clip-clop': 'Цокот копыт',
        'Neigh, whinny': 'Ржание',
        'Cattle, bovinae': 'Крупный рогатый скот',
        'Moo': 'Мычание',
        'Cowbell': 'Колокольчик коровы',
        'Pig': 'Свинья',
        'Oink': 'Хрю',
        'Goat': 'Коза',
        'Bleat': 'Блеяние',
        'Sheep': 'Овца',
        'Fowl': 'Домашняя птица',
        'Chicken, rooster': 'Курица, петух',
        'Cluck': 'Кукареку',
        'Crowing, cock-a-doodle-doo': 'Кукареку',
        'Turkey': 'Индейка',
        'Gobble': 'Кулдыканье',
        'Duck': 'Утка',
        'Quack': 'Кря',
        'Goose': 'Гусь',
        'Honk': 'Гогот',
        'Wild animals': 'Дикие животные',
        'Roaring cats (lions, tigers)': 'Ревущие кошки (львы, тигры)',
        'Roar': 'Рев',
        'Bird': 'Птица',
        'Bird vocalization, bird call, bird song': 'Птичье пение',
        'Chirp, tweet': 'Чириканье',
        'Squawk': 'Крик птицы',
        'Pigeon, dove': 'Голубь',
        'Coo': 'Воркование',
        'Crow': 'Ворона',
        'Caw': 'Карканье',
        'Owl': 'Сова',
        'Hoot': 'Уханье',
        'Bird flight, flapping wings': 'Полет птицы, хлопанье крыльями',
        'Canidae, dogs, wolves': 'Псовые, собаки, волки',
        'Rodents, rats, mice': 'Грызуны, крысы, мыши',
        'Mouse': 'Мышь',
        'Patter': 'Топот',
        'Insect': 'Насекомое',
        'Cricket': 'Сверчок',
        'Mosquito': 'Комар',
        'Fly, housefly': 'Муха',
        'Buzz': 'Жужжание',
        'Bee, wasp, etc.': 'Пчела, оса и т.д.',
        'Frog': 'Лягушка',
        'Croak': 'Кваканье',
        'Snake': 'Змея',
        'Rattle': 'Гремучая змея',
        'Whale vocalization': 'Звуки кита',
        'Music': 'Музыка',
        'Musical instrument': 'Музыкальный инструмент',
        'Plucked string instrument': 'Щипковый струнный инструмент',
        'Guitar': 'Гитара',
        'Electric guitar': 'Электрогитара',
        'Bass guitar': 'Бас-гитара',
        'Acoustic guitar': 'Акустическая гитара',
        'Steel guitar, slide guitar': 'Стил-гитара, слайд-гитара',
        'Tapping (guitar technique)': 'Тэппинг (гитарная техника)',
        'Strum': 'Бренчание',
        'Banjo': 'Банджо',
        'Sitar': 'Ситара',
        'Mandolin': 'Мандолина',
        'Zither': 'Цитра',
        'Ukulele': 'Укулеле',
        'Keyboard (musical)': 'Клавиатура (музыкальная)',
        'Piano': 'Пианино',
        'Electric piano': 'Электропиано',
        'Organ': 'Орган',
        'Electronic organ': 'Электроорган',
        'Hammond organ': 'Орган Хаммонда',
        'Synthesizer': 'Синтезатор',
        'Sampler': 'Сэмплер',
        'Harpsichord': 'Клавесин',
        'Percussion': 'Ударные',
        'Drum kit': 'Ударная установка',
        'Drum machine': 'Драм-машина',
        'Drum': 'Барабан',
        'Snare drum': 'Малый барабан',
        'Rimshot': 'Римшот',
        'Drum roll': 'Дробь барабана',
        'Bass drum': 'Бас-барабан',
        'Timpani': 'Литавры',
        'Tabla': 'Табла',
        'Cymbal': 'Тарелки',
        'Hi-hat': 'Хай-хэт',
        'Wood block': 'Деревянный блок',
        'Tambourine': 'Бубен',
        'Rattle (instrument)': 'Погремушка (инструмент)',
        'Maraca': 'Маракасы',
        'Gong': 'Гонг',
        'Tubular bells': 'Колокольчики',
        'Mallet percussion': 'Ударные с молоточками',
        'Marimba, xylophone': 'Маримба, ксилофон',
        'Glockenspiel': 'Колокольчики',
        'Vibraphone': 'Виброфон',
        'Steelpan': 'Стальной барабан',
        'Orchestra': 'Оркестр',
        'Brass instrument': 'Медный духовой инструмент',
        'French horn': 'Валторна',
        'Trumpet': 'Труба',
        'Trombone': 'Тромбон',
        'Bowed string instrument': 'Смычковый струнный инструмент',
        'String section': 'Струнная секция',
        'Violin, fiddle': 'Скрипка',
        'Pizzicato': 'Пиццикато',
        'Cello': 'Виолончель',
        'Double bass': 'Контрабас',
        'Wind instrument, woodwind instrument': 'Духовой инструмент, деревянный духовой инструмент',
        'Flute': 'Флейта',
        'Saxophone': 'Саксофон',
        'Clarinet': 'Кларнет',
        'Harp': 'Арфа',
        'Bell': 'Колокол',
        'Church bell': 'Церковный колокол',
        'Jingle bell': 'Колокольчик',
        'Bicycle bell': 'Велосипедный звонок',
        'Tuning fork': 'Камертон',
        'Chime': 'Колокольчики',
        'Wind chime': 'Ветряные колокольчики',
        'Change ringing (campanology)': 'Перезвон (кампанология)',
        'Harmonica': 'Гармоника',
        'Accordion': 'Аккордеон',
        'Bagpipes': 'Волынка',
        'Didgeridoo': 'Диджериду',
        'Shofar': 'Шофар',
        'Theremin': 'Терменвокс',
        'Singing bowl': 'Поющая чаша',
        'Scratching (performance technique)': 'Скретчинг (техника исполнения)',
        'Pop music': 'Поп-музыка',
        'Hip hop music': 'Хип-хоп музыка',
        'Beatboxing': 'Битбокс',
        'Rock music': 'Рок-музыка',
        'Heavy metal': 'Хэви-метал',
        'Punk rock': 'Панк-рок',
        'Grunge': 'Гранж',
        'Progressive rock': 'Прогрессивный рок',
        'Rock and roll': 'Рок-н-ролл',
        'Psychedelic rock': 'Психоделический рок',
        'Rhythm and blues': 'Ритм-н-блюз',
        'Soul music': 'Соул',
        'Reggae': 'Регги',
        'Country': 'Кантри',
        'Swing music': 'Свинг',
        'Bluegrass': 'Блюграсс',
        'Funk': 'Фанк',
        'Folk music': 'Народная музыка',
        'Middle Eastern music': 'Ближневосточная музыка',
        'Jazz': 'Джаз',
        'Disco': 'Диско',
        'Classical music': 'Классическая музыка',
        'Opera': 'Опера',
        'Electronic music': 'Электронная музыка',
        'House music': 'Хаус',
        'Techno': 'Техно',
        'Dubstep': 'Дабстеп',
        'Drum and bass': 'Драм-н-бейс',
        'Electronica': 'Электроника',
        'Electronic dance music': 'Электронная танцевальная музыка',
        'Ambient music': 'Эмбиент',
        'Trance music': 'Транс',
        'Music of Latin America': 'Музыка Латинской Америки',
        'Salsa music': 'Сальса',
        'Flamenco': 'Фламенко',
        'Blues': 'Блюз',
        'Music for children': 'Музыка для детей',
        'New-age music': 'Нью-эйдж',
        'Vocal music': 'Вокальная музыка',
        'A capella': 'А капелла',
        'Music of Africa': 'Африканская музыка',
        'Afrobeat': 'Афробит',
        'Christian music': 'Христианская музыка',
        'Gospel music': 'Госпел',
        'Music of Asia': 'Азиатская музыка',
        'Carnatic music': 'Карнатическая музыка',
        'Music of Bollywood': 'Музыка Болливуда',
        'Ska': 'Ска',
        'Traditional music': 'Традиционная музыка',
        'Independent music': 'Независимая музыка',
        'Song': 'Песня',
        'Background music': 'Фоновая музыка',
        'Theme music': 'Тематическая музыка',
        'Jingle (music)': 'Джингл',
        'Soundtrack music': 'Музыка к фильму',
        'Lullaby': 'Колыбельная',
        'Video game music': 'Музыка к видеоиграм',
        'Christmas music': 'Рождественская музыка',
        'Dance music': 'Танцевальная музыка',
        'Wedding music': 'Свадебная музыка',
        'Happy music': 'Радостная музыка',
        'Funny music': 'Смешная музыка',
        'Sad music': 'Грустная музыка',
        'Tender music': 'Нежная музыка',
        'Exciting music': 'Возбуждающая музыка',
        'Angry music': 'Злая музыка',
        'Scary music': 'Страшная музыка',
        'Wind': 'Ветер',
        'Rustling leaves': 'Шуршание листьев',
        'Wind noise (microphone)': 'Шум ветра (микрофон)',
        'Thunderstorm': 'Гроза',
        'Thunder': 'Гром',
        'Water': 'Вода',
        'Rain': 'Дождь',
        'Raindrop': 'Капля дождя',
        'Rain on surface': 'Дождь по поверхности',
        'Stream': 'Ручей',
        'Waterfall': 'Водопад',
        'Ocean': 'Океан',
        'Waves, surf': 'Волны, прибой',
        'Steam': 'Пар',
        'Gurgling': 'Бульканье',
        'Fire': 'Огонь',
        'Crackle': 'Треск',
        'Vehicle': 'Транспортное средство',
        'Boat, Water vehicle': 'Лодка, водное транспортное средство',
        'Sailboat, sailing ship': 'Парусник',
        'Rowboat, canoe, kayak': 'Лодка, каноэ, каяк',
        'Motorboat, speedboat': 'Моторная лодка, катер',
        'Ship': 'Корабль',
        'Motor vehicle (road)': 'Автомобиль (дорога)',
        'Car': 'Автомобиль',
        'Vehicle horn, car horn, honking': 'Автомобильный гудок',
        'Toot': 'Гудок',
        'Car alarm': 'Автомобильная сигнализация',
        'Power windows, electric windows': 'Электростеклоподъемники',
        'Skidding': 'Занос',
        'Tire squeal': 'Визг шин',
        'Car passing by': 'Проезжающий автомобиль',
        'Race car, auto racing': 'Гоночный автомобиль, автогонки',
        'Truck': 'Грузовик',
        'Air brake': 'Пневматический тормоз',
        'Air horn, truck horn': 'Воздушный гудок, гудок грузовика',
        'Reversing beeps': 'Звук заднего хода',
        'Ice cream truck, ice cream van': 'Мороженщик',
        'Bus': 'Автобус',
        'Emergency vehicle': 'Транспорт экстренной помощи',
        'Police car (siren)': 'Полицейская машина (сирена)',
        'Ambulance (siren)': 'Скорая помощь (сирена)',
        'Fire engine, fire truck (siren)': 'Пожарная машина (сирена)',
        'Motorcycle': 'Мотоцикл',
        'Traffic noise, roadway noise': 'Шум дороги',
        'Rail transport': 'Железнодорожный транспорт',
        'Train': 'Поезд',
        'Train whistle': 'Гудок поезда',
        'Train horn': 'Гудок поезда',
        'Railroad car, train wagon': 'Железнодорожный вагон',
        'Train wheels squealing': 'Скрип колес поезда',
        'Subway, metro, underground': 'Метро',
        'Aircraft': 'Воздушное судно',
        'Aircraft engine': 'Авиационный двигатель',
        'Jet engine': 'Реактивный двигатель',
        'Propeller, airscrew': 'Пропеллер',
        'Helicopter': 'Вертолет',
        'Fixed-wing aircraft, airplane': 'Самолет',
        'Bicycle': 'Велосипед',
        'Skateboard': 'Скейтборд',
        'Engine': 'Двигатель',
        'Light engine (high frequency)': 'Легкий двигатель (высокая частота)',
        'Dental drill, dentist\'s drill': 'Стоматологическая бормашина',
        'Lawn mower': 'Газонокосилка',
        'Chainsaw': 'Бензопила',
        'Medium engine (mid frequency)': 'Средний двигатель (средняя частота)',
        'Heavy engine (low frequency)': 'Тяжелый двигатель (низкая частота)',
        'Engine knocking': 'Стук двигателя',
        'Engine starting': 'Запуск двигателя',
        'Idling': 'Холостой ход',
        'Accelerating, revving, vroom': 'Ускорение, обороты, врум',
        'Door': 'Дверь',
        'Doorbell': 'Дверной звонок',
        'Ding-dong': 'Дин-дон',
        'Sliding door': 'Раздвижная дверь',
        'Slam': 'Хлопок',
        'Knock': 'Стук',
        'Tap': 'Постукивание',
        'Squeak': 'Скрип',
        'Cupboard open or close': 'Открытие или закрытие шкафа',
        'Drawer open or close': 'Открытие или закрытие ящика',
        'Dishes, pots, and pans': 'Посуда, кастрюли и сковородки',
        'Cutlery, silverware': 'Столовые приборы',
        'Chopping (food)': 'Нарезка (еда)',
        'Frying (food)': 'Жарка (еда)',
        'Microwave oven': 'Микроволновая печь',
        'Blender': 'Блендер',
        'Water tap, faucet': 'Водопроводный кран',
        'Sink (filling or washing)': 'Раковина (наполнение или мытье)',
        'Bathtub (filling or washing)': 'Ванна (наполнение или мытье)',
        'Hair dryer': 'Фен',
        'Toilet flush': 'Слив унитаза',
        'Toothbrush': 'Зубная щетка',
        'Electric toothbrush': 'Электрическая зубная щетка',
        'Vacuum cleaner': 'Пылесос',
        'Zipper (clothing)': 'Молния (одежда)',
        'Keys jangling': 'Звон ключей',
        'Coin (dropping)': 'Монета (падение)',
        'Scissors': 'Ножницы',
        'Electric shaver, electric razor': 'Электробритва',
        'Shuffling cards': 'Перетасовка карт',
        'Typing': 'Печатание',
        'Typewriter': 'Пишущая машинка',
        'Computer keyboard': 'Компьютерная клавиатура',
        'Writing': 'Письмо',
        'Alarm': 'Тревога',
        'Telephone': 'Телефон',
        'Telephone bell ringing': 'Телефонный звонок',
        'Ringtone': 'Мелодия звонка',
        'Telephone dialing, DTMF': 'Набор номера телефона, DTMF',
        'Dial tone': 'Гудок',
        'Busy signal': 'Сигнал занятости',
        'Alarm clock': 'Будильник',
        'Siren': 'Сирена',
        'Civil defense siren': 'Сигнал гражданской обороны',
        'Buzzer': 'Зуммер',
        'Smoke detector, smoke alarm': 'Детектор дыма',
        'Fire alarm': 'Пожарная сигнализация',
        'Foghorn': 'Туманный горн',
        'Whistle': 'Свисток',
        'Steam whistle': 'Паровой свисток',
        'Mechanisms': 'Механизмы',
        'Ratchet, pawl': 'Храповик',
        'Clock': 'Часы',
        'Tick': 'Тик',
        'Tick-tock': 'Тик-так',
        'Gears': 'Шестерни',
        'Pulleys': 'Шкивы',
        'Sewing machine': 'Швейная машинка',
        'Mechanical fan': 'Механический вентилятор',
        'Air conditioning': 'Кондиционер',
        'Cash register': 'Кассовый аппарат',
        'Printer': 'Принтер',
        'Camera': 'Камера',
        'Single-lens reflex camera': 'Однообъективный зеркальный фотоаппарат',
        'Tools': 'Инструменты',
        'Hammer': 'Молоток',
        'Jackhammer': 'Отбойный молоток',
        'Sawing': 'Распиловка',
        'Filing (rasp)': 'Напильник',
        'Sanding': 'Шлифовка',
        'Power tool': 'Электроинструмент',
        'Drill': 'Дрель',
        'Explosion': 'Взрыв',
        'Gunshot, gunfire': 'Выстрел',
        'Machine gun': 'Пулемет',
        'Fusillade': 'Залп',
        'Artillery fire': 'Артиллерийский огонь',
        'Cap gun': 'Игрушечный пистолет',
        'Fireworks': 'Фейерверк',
        'Firecracker': 'Петарда',
        'Burst, pop': 'Хлопок',
        'Eruption': 'Извержение',
        'Boom': 'Бум',
        'Wood': 'Дерево',
        'Chop': 'Рубка',
        'Splinter': 'Щепка',
        'Crack': 'Треск',
        'Glass': 'Стекло',
        'Chink, clink': 'Звон',
        'Shatter': 'Разбитие',
        'Liquid': 'Жидкость',
        'Splash, splatter': 'Брызги',
        'Slosh': 'Плеск',
        'Squish': 'Хлюп',
        'Drip': 'Капля',
        'Pour': 'Наливание',
        'Trickle, dribble': 'Капание',
        'Gush': 'Бурный поток',
        'Fill (with liquid)': 'Наполнение (жидкостью)',
        'Spray': 'Распыление',
        'Pump (liquid)': 'Насос (жидкость)',
        'Stir': 'Размешивание',
        'Boiling': 'Кипение',
        'Sonar': 'Сонар',
        'Arrow': 'Стрела',
        'Whoosh, swoosh, swish': 'Свист',
        'Thump, thud': 'Глухой удар',
        'Thunk': 'Глухой звук',
        'Electronic tuner': 'Электронный тюнер',
        'Effects unit': 'Блок эффектов',
        'Chorus effect': 'Эффект хоруса',
        'Basketball bounce': 'Отскок баскетбольного мяча',
        'Bang': 'Бум',
        'Slap, smack': 'Шлепок',
        'Whack, thwack': 'Удар',
        'Smash, crash': 'Разбитие',
        'Breaking': 'Разбитие',
        'Bouncing': 'Отскок',
        'Whip': 'Хлыст',
        'Flap': 'Хлопок',
        'Scratch': 'Царапина',
        'Scrape': 'Скрип',
        'Rub': 'Трение',
        'Roll': 'Качение',
        'Crushing': 'Дробление',
        'Crumpling, crinkling': 'Смятие',
        'Tearing': 'Разрыв',
        'Beep, bleep': 'Писк',
        'Ping': 'Пинг',
        'Ding': 'Динь',
        'Clang': 'Лязг',
        'Squeal': 'Визг',
        'Creak': 'Скрип',
        'Rustle': 'Шуршание',
        'Whir': 'Жужжание',
        'Clatter': 'Грохот',
        'Sizzle': 'Шипение',
        'Clicking': 'Щелчок',
        'Clickety-clack': 'Щелк-клац',
        'Rumble': 'Грохот',
        'Plop': 'Плюх',
        'Jingle, tinkle': 'Звон',
        'Hum': 'Гул',
        'Zing': 'Зинг',
        'Boing': 'Бойнг',
        'Crunch': 'Хруст',
        'Silence': 'Тишина',
        'Sine wave': 'Синусоида',
        'Harmonic': 'Гармоника',
        'Chirp tone': 'Чирикающий тон',
        'Sound effect': 'Звуковой эффект',
        'Pulse': 'Пульс',
        'Inside, small room': 'Внутри, маленькая комната',
        'Inside, large room or hall': 'Внутри, большая комната или зал',
        'Inside, public space': 'Внутри, общественное пространство',
        'Outside, urban or manmade': 'Снаружи, городское или созданное человеком',
        'Outside, rural or natural': 'Снаружи, сельское или природное',
        'Reverberation': 'Реверберация',
        'Echo': 'Эхо',
        'Noise': 'Шум',
        'Environmental noise': 'Шум окружающей среды',
        'Static': 'Статика',
        'Mains hum': 'Гул сети',
        'Distortion': 'Искажение',
        'Sidetone': 'Боковой тон',
        'Cacophony': 'Какофония',
        'White noise': 'Белый шум',
        'Pink noise': 'Розовый шум',
        'Throbbing': 'Пульсация',
        'Vibration': 'Вибрация',
        'Television': 'Телевизор',
        'Radio': 'Радио',
        'Field recording': 'Полевая запись'
    }


def visualize_spectrogram(args):
    """Визуализация спектрограммы и предсказаний модели."""
    # Загрузка аудио
    (waveform, sr) = librosa.core.load(args.audio_path, sr=32000, mono=True)
    waveform = waveform[None, :]  # (1, audio_length)
    
    # Загрузка модели
    Model = eval(args.model_type)
    model = Model(sample_rate=32000, window_size=1024, 
                 hop_size=320, mel_bins=64, fmin=50, fmax=14000, 
                 classes_num=classes_num)
    
    checkpoint = torch.load(args.checkpoint_path, map_location=torch.device('cpu'))
    model.load_state_dict(checkpoint['model'])
    
    # Перемещение модели на устройство
    device = torch.device('cuda') if args.cuda and torch.cuda.is_available() else torch.device('cpu')
    model = model.to(device)
    model.eval()
    
    # Получение предсказаний
    with torch.no_grad():
        waveform = move_data_to_device(waveform, device)
        batch_output_dict = model(waveform)
        framewise_output = batch_output_dict['framewise_output'].data.cpu().numpy()[0]
        clipwise_output = batch_output_dict['clipwise_output'].data.cpu().numpy()[0]
    
    # Создание фигуры
    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(15, 10), gridspec_kw={'height_ratios': [3, 1]})
    
    # Визуализация спектрограммы
    mel_spec = librosa.feature.melspectrogram(y=waveform[0].cpu().numpy(), 
                                            sr=32000, 
                                            n_fft=1024, 
                                            hop_length=320, 
                                            n_mels=64, 
                                            fmin=50, 
                                            fmax=14000)
    mel_spec_db = librosa.power_to_db(mel_spec, ref=np.max)
    
    im = ax1.imshow(mel_spec_db, 
                    aspect='auto', 
                    origin='lower',
                    cmap='viridis')  # Используем более приятную цветовую схему
    ax1.set_title('Спектрограмма', fontsize=14, pad=20)
    ax1.set_xlabel('Время (кадры)', fontsize=12)
    ax1.set_ylabel('Частота (Мел)', fontsize=12)
    plt.colorbar(im, ax=ax1, format='%+2.0f dB')
    
    # Визуализация предсказаний
    # Получаем топ-10 классов из clipwise_output для отображения
    sorted_indexes = np.argsort(clipwise_output)[::-1]
    top_k = 10
    top_indexes = sorted_indexes[:top_k]
    
    # Подготавливаем данные для отображения (обратный порядок для отображения)
    display_labels = [get_russian_labels().get(labels[idx], labels[idx]) for idx in top_indexes][::-1]
    display_framewise_output = framewise_output[:, top_indexes].T[::-1]
    
    # Используем более приятную цветовую схему для тепловой карты
    im_pred = ax2.imshow(display_framewise_output, 
                        origin='lower', 
                        aspect='auto', 
                        cmap='RdYlBu_r',  # Более приятная цветовая схема
                        extent=[0, display_framewise_output.shape[1], -0.5, len(display_labels) - 0.5])
    
    ax2.set_yticks(np.arange(len(display_labels)))
    ax2.set_yticklabels(display_labels)
    ax2.set_xlabel('Время (кадры)', fontsize=12)
    ax2.set_title('Активность звуковых событий во времени', fontsize=14, pad=20)
    
    # Добавляем цветовую шкалу для нижней диаграммы
    cbar = plt.colorbar(im_pred, ax=ax2, format='%.2f')
    cbar.set_label('Вероятность', fontsize=12)
    
    plt.tight_layout()
    
    # Сохранение фигуры
    fig_path = os.path.join('results', '{}.png'.format(get_filename(args.audio_path)))
    create_folder(os.path.dirname(fig_path))
    plt.savefig(fig_path, dpi=300, bbox_inches='tight')
    print('Изображение сохранено в {}'.format(fig_path))
    
    plt.show()


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Visualize spectrogram of an audio clip.')
    parser.add_argument('--sample_rate', type=int, default=32000)
    parser.add_argument('--window_size', type=int, default=1024)
    parser.add_argument('--hop_size', type=int, default=320)
    parser.add_argument('--mel_bins', type=int, default=64)
    parser.add_argument('--fmin', type=int, default=50)
    parser.add_argument('--fmax', type=int, default=14000)
    parser.add_argument('--audio_path', type=str, required=True)
    parser.add_argument('--model_type', type=str, default='Cnn14')
    parser.add_argument('--checkpoint_path', type=str, default='weights/cnn14.pth')
    parser.add_argument('--cuda', action='store_true', default=False)
    
    args = parser.parse_args()
    visualize_spectrogram(args) 